import { type NextRequest, NextResponse } from "next/server"

const caseStudiesDatabase = [
  // Indian startups
  {
    id: "byjus",
    name: "BYJU'S",
    category: "EdTech",
    peakValuation: "$22B",
    currentStatus: "Restructuring",
    yearFounded: 2011,
    yearOfDecline: 2023,
    country: "India",
    founder: "Byju Raveendran",
    employees: "50,000+ (at peak)",
    summary:
      "BYJU'S was once India's most valuable startup and the world's most valuable edtech company. Its spectacular fall from a $22 billion valuation to near worthlessness represents one of the biggest corporate collapses in Indian startup history. The company burned through billions in acquisitions without proper integration, faced accounting irregularities, and suffered from unsustainable growth tactics.",
    image: "https://logo.clearbit.com/byjus.com",
    timeline: [
      { year: 2011, event: "Founded by Byju Raveendran in Bangalore" },
      { year: 2015, event: "Launched BYJU'S learning app" },
      { year: 2019, event: "Became India's most valuable edtech startup" },
      { year: 2021, event: "Acquired Aakash Educational Services for $1B" },
      { year: 2022, event: "Peak valuation of $22 billion reached" },
      { year: 2023, event: "Mass layoffs, auditor resignations, investor lawsuits" },
      { year: 2024, event: "NCLT orders insolvency proceedings" },
    ],
    keyFailures: [
      "Aggressive acquisitions ($2.5B+ spent) without proper integration or synergies",
      "Delayed financial filings and auditor resignations due to accounting irregularities",
      "Unsustainable growth model relying on aggressive sales tactics and expensive customer acquisition",
      "Poor corporate governance with centralized decision-making and lack of independent oversight",
    ],
    lessons: [
      "Growth at all costs is not sustainable without profitability path",
      "Acquisitions need integration planning, not just deal-making",
      "Corporate governance matters especially as companies scale",
      "Sales pressure tactics damage brand trust long-term",
    ],
    sources: [
      { name: "Reuters", url: "https://reuters.com" },
      { name: "Economic Times", url: "https://economictimes.com" },
      { name: "TechCrunch", url: "https://techcrunch.com" },
    ],
  },
  {
    id: "gomechanic",
    name: "GoMechanic",
    category: "Auto Services",
    peakValuation: "$850M",
    currentStatus: "Distressed sale",
    yearFounded: 2016,
    yearOfDecline: 2023,
    country: "India",
    founder: "Amit Bhardwaj",
    employees: "1,500+",
    summary:
      "GoMechanic was India's largest car servicing network startup that promised to disrupt the auto maintenance industry. The company admitted to financial reporting irregularities, leading to layoffs and a distressed asset sale. Internal mismanagement, operational leakage, and over-expansion beyond operational capacity were the key culprits.",
    image: "/images/gomechanic.jpg",
    timeline: [
      { year: 2016, event: "Founded to revolutionize car servicing" },
      { year: 2020, event: "Raised Series B funding" },
      { year: 2021, event: "Peak valuation of $850M" },
      { year: 2023, event: "Financial reporting irregularities disclosed" },
      { year: 2023, event: "Mass layoffs announced" },
      { year: 2023, event: "Distressed asset sale to stakeholders" },
    ],
    keyFailures: [
      "Financial reporting irregularities and accounting problems",
      "Rapid over-expansion without operational maturity",
      "Operational leakage and inefficiency in garage network management",
      "Misalignment between aggressive expansion and unit economics",
    ],
    lessons: [
      "Unit economics must be proven before scaling aggressively",
      "Operational metrics matter more than top-line growth",
      "Honest financial reporting is non-negotiable",
      "Franchise/network models need strong operational discipline",
    ],
    sources: [
      { name: "Mint", url: "https://mint.com" },
      { name: "Business Standard", url: "https://business-standard.com" },
    ],
  },
  {
    id: "zilingo",
    name: "Zilingo",
    category: "E-Commerce",
    peakValuation: "$1B",
    currentStatus: "Wound down",
    yearFounded: 2015,
    yearOfDecline: 2022,
    country: "Singapore/India",
    summary: "Fashion marketplace with India ops; governance probe and funding freeze led to shutdown.",
    keyFailures: ["Governance probe", "Cash flow crunch"],
    image: "https://logo.clearbit.com/zilingo.com",
    source: "https://zilingo.com",
  },
  {
    id: "peppertap",
    name: "PepperTap",
    category: "Grocery",
    peakValuation: "$51M",
    currentStatus: "Shut down",
    yearFounded: 2014,
    yearOfDecline: 2016,
    country: "India",
    summary: "Hyperlocal grocery delivery that shut due to unit economics and high burn.",
    keyFailures: ["Negative unit economics", "High discounts"],
    image: "https://logo.clearbit.com/peppertap.com",
    source: "https://peppertap.com",
  },
  {
    id: "localbanya",
    name: "LocalBanya",
    category: "Grocery",
    peakValuation: "—",
    currentStatus: "Shut down",
    yearFounded: 2012,
    yearOfDecline: 2015,
    country: "India",
    summary: "Mumbai-based online grocer that halted operations amid funding crunch.",
    keyFailures: ["Funding crunch", "Competition"],
    image: "https://logo.clearbit.com/localbanya.com",
    source: "http://localbanya.com",
  },
  {
    id: "tinyowl",
    name: "TinyOwl",
    category: "Food Tech",
    peakValuation: "$27M",
    currentStatus: "Merged/Shut",
    yearFounded: 2014,
    yearOfDecline: 2016,
    country: "India",
    summary: "Food ordering startup that faced rapid burn, layoffs, and eventual merger and shutdown.",
    keyFailures: ["Overexpansion", "High burn"],
    image: "https://logo.clearbit.com/tinyowl.com",
    source: "https://tinyowl.com",
  },
  {
    id: "hike",
    name: "Hike Messenger",
    category: "Social Media",
    peakValuation: "$1.4B",
    currentStatus: "Pivoted/Shut",
    yearFounded: 2012,
    yearOfDecline: 2021,
    country: "India",
    summary: "Messaging app shut down core chat in 2021; could not compete with WhatsApp network effects.",
    keyFailures: ["Network effects", "Late pivot"],
    image: "https://logo.clearbit.com/hike.in",
    source: "https://hike.in",
  },

  // Global startups
  {
    id: "ftx",
    name: "FTX",
    category: "Cryptocurrency",
    peakValuation: "$32B",
    currentStatus: "Bankrupt",
    yearFounded: 2019,
    yearOfDecline: 2022,
    country: "USA",
    founder: "Sam Bankman-Fried",
    employees: "300+",
    summary:
      "FTX collapsed in November 2022 in one of the most spectacular corporate frauds in history. Founder Sam Bankman-Fried misappropriated customer funds and was convicted of fraud. The collapse exposed the dangers of inadequate corporate governance and the lack of independent board oversight in fast-growing fintech companies.",
    image: "https://logo.clearbit.com/ftx.com",
    timeline: [
      { year: 2019, event: "FTX founded by Sam Bankman-Fried" },
      { year: 2021, event: "Raised $900M at $18B valuation" },
      { year: 2022, event: "January: Raised Series C at $32B valuation" },
      { year: 2022, event: "November: CoinDesk exposes Alameda Research balance sheet" },
      { year: 2022, event: "November 11: FTX files for bankruptcy" },
      { year: 2023, event: "SBF arrested and charged with fraud" },
      { year: 2024, event: "SBF sentenced to 25 years in prison" },
    ],
    keyFailures: [
      "Massive fraud: customer deposits secretly transferred to Alameda Research",
      "No corporate controls, board oversight, or independent CFO",
      "Accounting done on QuickBooks with commingling of funds",
      "Misappropriation of billions for personal expenses and risky ventures",
    ],
    lessons: [
      "Board independence and oversight are critical, not optional",
      "Separate business entities must have strict financial controls",
      "Customer fund segregation is non-negotiable in fintech",
      "Rapid growth without compliance is a massive red flag",
    ],
    sources: [
      { name: "Reuters", url: "https://reuters.com" },
      { name: "Bloomberg", url: "https://bloomberg.com" },
    ],
  },
  {
    id: "wework",
    name: "WeWork",
    category: "Real Estate",
    peakValuation: "$47B",
    currentStatus: "Bankruptcy",
    yearFounded: 2010,
    yearOfDecline: 2023,
    country: "USA",
    founder: "Adam Neumann",
    employees: "6,000+",
    summary:
      "WeWork's business model was fundamentally flawed - taking long-term leases and subleasing them short-term with questionable unit economics. The company lost billions annually, and its failed 2019 IPO revealed the underlying problems. The company eventually filed for bankruptcy after hemorrhaging cash for over a decade.",
    image: "https://logo.clearbit.com/wework.com",
    timeline: [
      { year: 2010, event: "WeWork founded in New York" },
      { year: 2016, event: "SoftBank begins massive funding rounds" },
      { year: 2019, event: "Valued at $47B pre-IPO" },
      { year: 2019, event: "IPO pulled due to scrutiny of unit economics" },
      { year: 2020, event: "Adam Neumann resigns, SoftBank bailout" },
      { year: 2023, event: "Files for Chapter 11 bankruptcy" },
    ],
    keyFailures: [
      "Flawed business model: long-term leases with short-term subleases",
      "Consistently unprofitable with massive unit economics losses",
      "Failed IPO exposed the problems to public market scrutiny",
      "Over-leveraged with unsustainable burn rate",
    ],
    lessons: [
      "Unit economics must be positive or have clear path to profitability",
      "Real estate arbitrage without differentiation is dangerous",
      "IPO readiness requires transparent unit economics",
      "Founder-led companies need board oversight",
    ],
    sources: [
      { name: "Wall Street Journal", url: "https://wsj.com" },
      { name: "Financial Times", url: "https://ft.com" },
    ],
  },
  {
    id: "theranos",
    name: "Theranos",
    category: "Healthcare",
    peakValuation: "$9B",
    currentStatus: "Dissolved",
    yearFounded: 2003,
    yearOfDecline: 2018,
    country: "USA",
    founder: "Elizabeth Holmes",
    employees: "600+",
    summary:
      "Theranos claimed to revolutionize blood testing with a device that could perform comprehensive tests from a single drop of blood. The company's technology never worked as promised, and founder Elizabeth Holmes was convicted of fraud for making false claims to investors and regulators.",
    image: "https://logo.clearbit.com/theranos.com",
    timeline: [
      { year: 2003, event: "Theranos founded by Elizabeth Holmes" },
      { year: 2013, event: "Announced partnership with Walgreens" },
      { year: 2015, event: "Peak valuation of $9B, Holmes on Forbes richest list" },
      { year: 2015, event: "Wall Street Journal investigation begins" },
      { year: 2016, event: "FDA and CMS investigations launched" },
      { year: 2018, event: "Theranos shut down" },
      { year: 2022, event: "Holmes convicted of fraud, sentenced to 11 years" },
    ],
    keyFailures: [
      "Technology did not work as claimed - false promises about accuracy",
      "Misrepresentation to investors about device capabilities and validation",
      "Regulatory violations and safety concerns",
      "Deliberate deception of doctors, patients, and partners",
    ],
    lessons: [
      "Technology claims require independent verification",
      "Misrepresenting capabilities to investors is fraud",
      "Healthcare has strict regulatory requirements for a reason",
      "Charisma is not a substitute for working technology",
    ],
    sources: [
      { name: "Wall Street Journal", url: "https://wsj.com" },
      { name: "SEC Enforcement", url: "https://sec.gov" },
    ],
  },
  {
    id: "quibi",
    name: "Quibi",
    category: "Entertainment",
    peakValuation: "$1.75B",
    currentStatus: "Shut down",
    yearFounded: 2018,
    yearOfDecline: 2020,
    country: "USA",
    summary: "Short-form video platform shut down within 6 months; poor market timing and high content costs.",
    keyFailures: ["Wrong timing", "High burn", "Market mismatch"],
    image: "https://logo.clearbit.com/quibi.com",
    source: "https://quibi.com",
  },
  {
    id: "juul",
    name: "Juul",
    category: "Hardware",
    peakValuation: "$38B",
    currentStatus: "Declining",
    yearFounded: 2015,
    yearOfDecline: 2022,
    country: "USA",
    summary: "E-cigarette maker faced regulatory bans, lawsuits, and loss of market value due to health concerns.",
    keyFailures: ["Regulatory bans", "Health backlash", "Legal issues"],
    image: "https://logo.clearbit.com/juul.com",
    source: "https://juul.com",
  },
  {
    id: "groupon",
    name: "Groupon",
    category: "E-Commerce",
    peakValuation: "$16B (at IPO)",
    currentStatus: "Delisted/Declined",
    yearFounded: 2008,
    yearOfDecline: 2012,
    country: "USA",
    summary: "Daily deals platform's value plummeted post-IPO due to unsustainable unit economics and vendor disputes.",
    keyFailures: ["Poor unit economics", "Vendor churn", "Saturation"],
    image: "https://logo.clearbit.com/groupon.com",
    source: "https://groupon.com",
  },
  {
    id: "pets-com",
    name: "Pets.com",
    category: "E-Commerce",
    peakValuation: "$300M",
    currentStatus: "Bankrupt",
    yearFounded: 1998,
    yearOfDecline: 2000,
    country: "USA",
    summary: "Dot-com era e-commerce failed with unsustainable unit economics; became symbol of bubble burst.",
    keyFailures: ["Dot-com bubble", "No profitability", "Competition"],
    image: "https://logo.clearbit.com/pets.com",
    source: "https://pets.com",
  },
  {
    id: "jawbone",
    name: "Jawbone",
    category: "Hardware",
    peakValuation: "$3.2B",
    currentStatus: "Bankrupt",
    yearFounded: 1999,
    yearOfDecline: 2017,
    country: "USA",
    summary: "Wearable and audio company filed for bankruptcy; crowded market and product quality issues.",
    keyFailures: ["Product defects", "Market saturation", "Supply chain issues"],
    image: "https://logo.clearbit.com/jawbone.com",
    source: "https://jawbone.com",
  },
  {
    id: "vine",
    name: "Vine",
    category: "Social Media",
    peakValuation: "—",
    currentStatus: "Shut down",
    yearFounded: 2013,
    yearOfDecline: 2017,
    country: "USA",
    summary: "Twitter's short-form video platform shut down; couldn't compete with Instagram Stories and TikTok.",
    keyFailures: ["Competition", "Creator exodus", "No monetization"],
    image: "https://logo.clearbit.com/vine.co",
    source: "https://vine.co",
  },
  {
    id: "klarna",
    name: "Klarna",
    category: "FinTech",
    peakValuation: "$46B",
    currentStatus: "Declining",
    yearFounded: 2005,
    yearOfDecline: 2023,
    country: "Sweden",
    summary: "Buy-now-pay-later pioneer faced massive losses, layoffs, and valuation collapse amid economic slowdown.",
    keyFailures: ["Unsustainable burn", "Default rates", "Market saturation"],
    image: "https://logo.clearbit.com/klarna.com",
    source: "https://klarna.com",
  },
  {
    id: "robinhood",
    name: "Robinhood",
    category: "FinTech",
    peakValuation: "$11.7B (IPO)",
    currentStatus: "Delisted/Declining",
    yearFounded: 2013,
    yearOfDecline: 2022,
    country: "USA",
    summary: "Stock trading app lost 85% value post-IPO; GameStop saga, SEC scrutiny, and competitive pressure.",
    keyFailures: ["GameStop controversy", "SEC pressure", "Regulatory issues"],
    image: "https://logo.clearbit.com/robinhood.com",
    source: "https://robinhood.com",
  },
  {
    id: "codecademy",
    name: "Codecademy",
    category: "EdTech",
    peakValuation: "$405M (SPAC)",
    currentStatus: "Declining",
    yearFounded: 2011,
    yearOfDecline: 2022,
    country: "USA",
    summary: "Online coding bootcamp struggled with completion rates and monetization; SPAC listing didn't help.",
    keyFailures: ["Low completion", "Monetization issue", "Competition"],
    image: "https://logo.clearbit.com/codecademy.com",
    source: "https://codecademy.com",
  },
  {
    id: "affirm",
    name: "Affirm",
    category: "FinTech",
    peakValuation: "$13.2B (IPO)",
    currentStatus: "Declining",
    yearFounded: 2012,
    yearOfDecline: 2022,
    country: "USA",
    summary: "BNPL pioneer lost 95% value post-IPO; high default rates, merchant losses, and economic downturn.",
    keyFailures: ["Credit losses", "High defaults", "Unit economics"],
    image: "https://logo.clearbit.com/affirm.com",
    source: "https://affirm.com",
  },
  {
    id: "snapchat",
    name: "Snapchat (Early Challenges)",
    category: "Social Media",
    peakValuation: "$25B (IPO)",
    currentStatus: "Recovering",
    yearFounded: 2011,
    yearOfDecline: 2017,
    country: "USA",
    summary:
      "Social app faced major challenges post-IPO; redesign backlash and Instagram competition nearly killed it.",
    keyFailures: ["Failed redesign", "User backlash", "Competition"],
    image: "https://logo.clearbit.com/snapchat.com",
    source: "https://snapchat.com",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    category: "Music",
    peakValuation: "$700M",
    currentStatus: "Struggling",
    yearFounded: 2007,
    yearOfDecline: 2017,
    country: "Germany",
    summary:
      "Music streaming platform nearly folded; licensing costs and competition from Spotify caused massive losses.",
    keyFailures: ["Licensing disputes", "Competition", "Burn rate"],
    image: "https://logo.clearbit.com/soundcloud.com",
    source: "https://soundcloud.com",
  },
  {
    id: "foursquare",
    name: "Foursquare",
    category: "Social Media",
    peakValuation: "$500M+",
    currentStatus: "Pivoted",
    yearFounded: 2009,
    yearOfDecline: 2013,
    country: "USA",
    summary: "Location-based checkin app pivoted to B2B after failing to monetize; lost to Google and Apple.",
    keyFailures: ["No monetization", "Weak moat", "Competition"],
    image: "https://logo.clearbit.com/foursquare.com",
    source: "https://foursquare.com",
  },
  {
    id: "yext",
    name: "Yext",
    category: "SaaS",
    peakValuation: "$1.8B (IPO)",
    currentStatus: "Declining",
    yearFounded: 2006,
    yearOfDecline: 2022,
    country: "USA",
    summary: "Location data platform fell 80%+ from highs; retention issues and AI disruption.",
    keyFailures: ["Low retention", "AI competition", "Customer churn"],
    image: "https://logo.clearbit.com/yext.com",
    source: "https://yext.com",
  },
]

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  const { id } = params

  const caseStudy = caseStudiesDatabase.find((cs) => cs.id === id)

  if (!caseStudy) {
    return NextResponse.json({ error: "Case study not found" }, { status: 404 })
  }

  return NextResponse.json({ caseStudy })
}
