import { NextResponse } from "next/server"

// Mock trending startups data - combines real startup insights
const trendingStartups = [
  {
    id: "perplexity",
    name: "Perplexity AI",
    category: "AI/Search",
    description: "AI-powered search engine and reasoning engine challenging Google Search",
    currentStatus: "Growing",
    valuation: "$3B+",
    trend: "up",
    reason: "Backed by Amazon, Microsoft; gaining market share in AI search",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "AI/LLMs",
    description: "Creator of Claude LLM; focused on AI safety and alignment",
    currentStatus: "Growing",
    valuation: "$15B+",
    trend: "up",
    reason: "Strong funding from Google; Claude becoming mainstream; enterprise adoption",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    category: "AI/LLMs",
    description: "European AI company focusing on efficient open-source language models",
    currentStatus: "Growing",
    valuation: "$2B+",
    trend: "up",
    reason: "Strong backing; open-source models gaining adoption; EU focus",
  },
  {
    id: "stability-ai",
    name: "Stability AI",
    category: "AI/Image Generation",
    description: "Creator of Stable Diffusion; democratizing AI image generation",
    currentStatus: "Challenged",
    valuation: "$1B",
    trend: "sideways",
    reason: "Heavy competition from OpenAI DALL-E, Midjourney; licensing concerns",
  },
  {
    id: "humane-ai",
    name: "Humane AI",
    category: "Hardware/AI",
    description: "AI Pin device for contextual computing; post-smartphone paradigm",
    currentStatus: "Early Stage",
    valuation: "$850M",
    trend: "up",
    reason: "Raised $100M Series B; device received media coverage; futuristic vision",
  },
  {
    id: "fig",
    name: "Fig",
    category: "Developer Tools/AI",
    description: "AI-powered terminal autocomplete for developers",
    currentStatus: "Growing",
    valuation: "$66M",
    trend: "up",
    reason: "Strong developer adoption; raised Series B; solves real developer pain point",
  },
  {
    id: "magic",
    name: "Magic",
    category: "AI/No-Code",
    description: "AI that can control computers; RPA automation with LLMs",
    currentStatus: "Growing",
    valuation: "$500M+",
    trend: "up",
    reason: "Compelling demo videos; solving enterprise automation; raised significant funding",
  },
  {
    id: "waymo",
    name: "Waymo",
    category: "Autonomous Vehicles",
    description: "Google's self-driving car technology; now operating in multiple cities",
    currentStatus: "Scaling",
    valuation: "$30B+",
    trend: "up",
    reason: "Launched paid robotaxi service in SF and Phoenix; generating real revenue",
  },
  {
    id: "databricks",
    name: "Databricks",
    category: "Data/AI Infrastructure",
    description: "Data and AI platform; creator of Apache Spark; unified analytics",
    currentStatus: "Growing",
    valuation: "$43B",
    trend: "up",
    reason: "Strong enterprise adoption; raised $1.5B funding; critical data infrastructure",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Fintech/Payments",
    description: "Payment processing for internet; most valuable fintech company",
    currentStatus: "Mature/Growing",
    valuation: "$95B",
    trend: "up",
    reason: "Dominant in online payments; expanding into banking; strong growth",
  },
  {
    id: "figma",
    name: "Figma",
    category: "Design Tools",
    description: "Browser-based design tool killing Adobe XD; collaborative design",
    currentStatus: "Mature/Growing",
    valuation: "$20B",
    trend: "up",
    reason: "Massive designer adoption; expanding to whiteboarding and prototyping",
  },
  {
    id: "canva",
    name: "Canva",
    category: "Design/Creator Tools",
    description: "Democratizing graphic design; billions of templates and designs",
    currentStatus: "Mature/Growing",
    valuation: "$26B",
    trend: "up",
    reason: "Strong growth globally; expanded to video, presentation, website tools",
  },
  {
    id: "notion",
    name: "Notion",
    category: "Productivity/No-Code",
    description: "All-in-one workspace for notes, databases, wikis, and project management",
    currentStatus: "Growing",
    valuation: "$10B",
    trend: "up",
    reason: "Massive creator and team adoption; expanding to AI features; strong growth",
  },
  {
    id: "retool",
    name: "Retool",
    category: "Developer Tools/No-Code",
    description: "Rapid internal tool builder; visual development for business applications",
    currentStatus: "Growing",
    valuation: "$1.5B",
    trend: "up",
    reason: "Strong enterprise adoption; solving real developer time problem; $50M Series C",
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "No-Code/Productivity",
    description: "Visual database and workflow builder; spreadsheet meets database",
    currentStatus: "Growing",
    valuation: "$11B",
    trend: "up",
    reason: "Strong developer and no-code adoption; expanding automation capabilities",
  },
]

export async function GET() {
  return NextResponse.json({
    trendingStartups,
    timestamp: new Date().toISOString(),
    note: "This is mock trending startup data. In production, this would integrate with Crunchbase, PitchBook, or AngelList APIs for real-time data.",
  })
}
